spring:
  profiles:
    active: prod

  datasource:
      url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.pw}
      driver: ${spring.datasource.driver}