spring:
  profiles:
    active: local

  datasource:
      url: ${MYSQL_URL}
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASSWORD}
      driver: ${MYSQL_DRIVER}



mybatis:
  mapper-locations: classpath:mapper/**/*.xml