spring:
  profiles:
    active: prod
  location: classpath:/application-prod.yml

  datasource:
      url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver: ${spring.datasource.driver}